/**
 * /ags/ideas - Browse AI-Generated Startup Ideas
 */

'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

interface Idea {
  id: string;
  name: string;
  tagline: string;
  market: {
    tam: string;
    growth: string;
    segment: string;
  };
  revenueModel: string;
  techStack: string[];
  score: number;
  generatedAt: string;
  status: string;
  applicationsCount: number;
}

export default function IdeasBrowsePage() {
  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    fetchIdeas();
  }, []);

  async function fetchIdeas() {
    try {
      setLoading(true);
      const response = await fetch('/api/ags/ideas');
      
      if (!response.ok) {
        throw new Error('Failed to fetch ideas');
      }

      const data = await response.json();
      setIdeas(data.ideas);
      setTotal(data.total);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500 mx-auto mb-4"></div>
          <p className="text-gray-400">Loading ideas...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-500 mb-4">Error: {error}</p>
          <button
            onClick={fetchIdeas}
            className="px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-900 to-blue-900 py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl font-bold mb-4">🧬 AI-Generated Startup Ideas</h1>
          <p className="text-xl text-gray-300 mb-6">
            Pre-validated startup ideas generated by AI. Get $500K funding + AI co-founder.
          </p>
          <div className="flex gap-6 text-sm">
            <div>
              <span className="text-purple-400 font-bold">{total}</span>
              <span className="text-gray-400"> validated ideas</span>
            </div>
            <div>
              <span className="text-purple-400 font-bold">$500K</span>
              <span className="text-gray-400"> funding per idea</span>
            </div>
            <div>
              <span className="text-purple-400 font-bold">85+</span>
              <span className="text-gray-400"> quality score</span>
            </div>
          </div>
        </div>
      </div>

      {/* Ideas Grid */}
      <div className="max-w-6xl mx-auto px-6 py-12">
        {ideas.length === 0 ? (
          <div className="text-center text-gray-400 py-12">
            <p className="text-xl mb-4">No validated ideas yet.</p>
            <p>Check back soon! New ideas are generated daily.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {ideas.map(idea => (
              <IdeaCard key={idea.id} idea={idea} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function IdeaCard({ idea }: { idea: Idea }) {
  return (
    <Link href={`/ags/ideas/${idea.id}`}>
      <div className="bg-gray-800 rounded-lg p-6 hover:bg-gray-750 transition-colors cursor-pointer border border-gray-700 hover:border-purple-500">
        {/* Score Badge */}
        <div className="flex justify-between items-start mb-4">
          <h3 className="text-xl font-bold text-white">{idea.name}</h3>
          <div className="bg-purple-600 text-white px-3 py-1 rounded-full text-sm font-bold">
            {idea.score}/100
          </div>
        </div>

        {/* Tagline */}
        <p className="text-gray-300 mb-4">{idea.tagline}</p>

        {/* Market */}
        <div className="space-y-2 mb-4">
          <div className="flex items-center gap-2 text-sm">
            <span className="text-gray-500">📈</span>
            <span className="text-gray-400">{idea.market.tam} TAM, {idea.market.growth} growth</span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-gray-500">💰</span>
            <span className="text-gray-400">{idea.revenueModel}</span>
          </div>
        </div>

        {/* Tech Stack */}
        <div className="flex flex-wrap gap-2 mb-4">
          {idea.techStack.slice(0, 3).map(tech => (
            <span key={tech} className="bg-gray-700 text-gray-300 px-2 py-1 rounded text-xs">
              {tech}
            </span>
          ))}
          {idea.techStack.length > 3 && (
            <span className="text-gray-500 text-xs">+{idea.techStack.length - 3} more</span>
          )}
        </div>

        {/* Applications Count */}
        <div className="text-sm text-gray-500 mb-4">
          {idea.applicationsCount} {idea.applicationsCount === 1 ? 'application' : 'applications'}
        </div>

        {/* CTA */}
        <div className="text-purple-400 hover:text-purple-300 font-semibold flex items-center gap-2">
          View Details
          <span>→</span>
        </div>
      </div>
    </Link>
  );
}
